INSERT INTO pregunta (categoriaId, pregunta, respuestaCorrecta, respuestaInCorrecta1, respuestaInCorrecta2, respuestaInCorrecta3) VALUES
(13, '¿Qué significan las letras en la zona horaria GMT?', 'Hora media de Greenwich', 'Hora global del meridiano', 'La hora del hombre de Glasgow', 'Tiempo medio general'),
(13, '¿Qué palabra representa la letra T en el alfabeto fonético de la OTAN?', 'Tango', 'Taxi', 'Turkey (Pavo)', 'Target (Objetivo)'),
(13, '¿Cuál es la profesión de la madre de Elon Musk, Maye Musk?', 'Modelo', 'Profesora', 'Bióloga', 'Música'),
(13, '¿Quién inventó la primera barra de chocolate en 1847?', 'Joseph Fry', 'Andrew Johnson', 'John Cadbury', 'John Tyler'),
(13, '¿Qué producto vendió originalmente Nokia, la empresa de telecomunicaciones?', 'Papel', 'Teléfonos', 'Computadoras', 'Procesadores'),
(13, '¿Cuál es la característica que define a alguien que se describe como hirsuto?', 'Peludo', 'Brusco', 'Divertido', 'Alto'),
(13, '¿Cómo se llamaba el equipo de lucha libre profesional de la WWF formado por los luchadores Axe y Smash?', 'Demolition', 'The Dream Team', 'The Bushwhackers', 'The British Bulldogs'),
(13, '¿Cuál fue el tercer país en tener un restaurante McDonald´s?', 'Costa Rica', 'Japón', 'Francia', 'Australia'),
(13, '¿Quién fundó la Academia Khan?', 'Sal Khan', 'Ben Khan', 'Kitt Khan', 'Adel Khan'),
(13, '¿Quién es la persona más joven en recibir un Premio Nobel?', 'Malala Yousafzai', 'Lawrence Bragg', 'Werner Heisenberg', 'Yasser Arafat'),
(13, '¿En qué dirección mira la Estatua de la Libertad?', 'Sureste', 'Sur oeste', 'Noroeste', 'Noreste'),
(13, '¿Qué significa la "G" en "G-Man"?', 'Gobierno', 'Going (Ir)', 'Ghost (Fantasma)', 'Geronimo'),
(13, '¿Qué es un Burgee?', 'Una bandera', 'Una cuerda', 'Una ventana', 'Un tipo de comida'),
(13, '¿Qué estrella de cine tiene su estatua en Leicester Square?', 'Charlie Chaplin', 'Paul Newman', 'Rowan Atkinson', 'Alfred Hitchcock'),
(13, '¿Qué es Tasmania?', 'Un estado australiano', 'Un sabor del helado de Ben y Jerry', 'Un trastorno psicológico', 'El nombre de un personaje de Looney Toons'),
(13, 'En una entrevista de la CBS de 1994, el cofundador de Microsoft, Bill Gates ¿Qué truco inusual realizó ante la cámara?', 'Saltar sobre una silla de oficina', 'Saltar hacia atrás sobre un escritorio', 'Pararse sobre su cabeza', 'Escribir en un teclado mientras está parado de manos'),
(13, '¿Cuál de los siguientes edificios es un ejemplo de una estructura construida principalmente en el estilo arquitectónico Art Deco?', 'Niagara Mohawk Building', 'Taipei 101', 'One Detroit Center', 'Westendstrasse 1'),
(13, '¿La nefelococigia es la práctica de hacer qué?', 'Encontrar formas en las nubes', 'Dormir con los ojos abiertos', 'Romper cristales con la voz', 'Nadar en agua helada'),
(13, '¿La estación central de Ámsterdam está hermanada con qué estación?', 'London Liverpool Street', 'Frankfurt (principal) Hauptbahnhof', 'Paris Gare du Nord', 'Bruselas Midi'),
(2, '¿Cuál es la capital de Australia?', 'Canberra', 'Sydney', 'Melbourne', 'Brisbane'),
(2, '¿Qué estado de EE.UU. tiene la mayor población?', 'California', 'Nueva York', 'Texas', 'Florida'),
(2, '¿Qué Cuál es la capital de Eslovaquia?', 'Bratislava', 'Sofía', 'Ljubljana', 'Sarajevo'),
(2, 'Bir Tawil, una franja de tierra deshabitada que no ha sido reclamada por ningun país, que se encuentra a lo largo de la frontera de qué dos países ¿Cuáles son?', 'Egipto y Sudán', 'Israel y Jordania', 'Chad y Libia', 'Irak y Arabia Saudita'),
(2, '¿Cuántos condados hay en la República de Irlanda?', '26', '32', '28', '30'),
(2, '¿Cuál es la capital de Indonesia?', 'Yakarta', 'Bandung', 'Medan', 'Palembang'),
(2, '¿Cuál de estos países es el más pequeño en términos de población?', 'Noruega', 'Eslovaquia', 'Finlandia', 'Hong Kong'),
(2, '¿Cuál de estas NO es una isla que forma parte de Filipinas?', 'Java', 'Luzón', 'Mindanao', 'Palawan'),
(2, '¿Qué ciudad europea tiene el mayor kilometraje de canales del mundo?', 'Birmingham', 'Venecia', 'Ámsterdam', 'Berlín'),
(2, '¿Cuántos estados hay en Australia?', '6', '7', '8', '5'),
(2, '¿Dónde encontrarías la "Plaza de España"?"', 'Roma, Italia', 'Barcelona, España', 'Berlín, Alemania', 'Londres, Inglaterra'),
(2, '¿En qué país se encuentra Tallin?', 'Estonia', 'Finlandia', 'Suecia', 'Polonia'),
(2, 'Las siguientes provincias españolas están ubicadas en la zona norte de España excepto:', 'Murcia', 'Asturias', 'Navarra', 'León'),
(2, '¿Qué país no tiene salida al mar junto a Sudáfrica?', 'Lesotho', 'Swazilandia', 'Botswanav', 'Zimbabwe'),
(2, '¿Cuál es la capital de los Estados Unidos', 'Washington, DC', 'Los Ángeles, CA', 'Nueva York, NY', 'Houston, TX'),
(2, '¿Cuál no es un país de África?', 'Guyana', 'Senegal', 'Liberia', 'Somalia'),
(2, '¿Con cuántos países tiene frontera terrestre España?', '5', '2', '3', '4'),
(2, '¿Cuál de estas NO es una ciudad de Arabia Saudita?', 'Dubai', 'Riyadh', 'Mecca', 'Medina'),
(2, '¿Qué dos países actuales solían ser conocidos como la región de Rhodesia entre las décadas de 1890 y 1980?', 'Zambia y Zimbabwe', 'Togo y Benin', 'Lesotho y Suazilandia', 'Ruanda y Burundi'),
(2, '¿Cuál es la capital del Perú?', 'Lima', 'Santiago', 'Montevideo', 'Buenos Aires'),
(2, 'En el Sureste de Asia ¿Qué país controla las islas Andaman y Nicobar ?', 'India', 'Vietnam', 'Tailandia', 'Indonesia'),
(2, '¿En qué ciudad está ubicada Big Nickel en Canadá?', 'Sudbury, Ontario', 'Calgary, Alberta', 'Halifax, Nova Scotia', 'Victoria, British Columbia'),
(3, '¿Cuántas versiones en pintura y pastel de "El Grito" se cree que produjo el pintor noruego Edvard Munch?', '4', '1', '3', '2'),
(3, '¿El pintor Piet Mondrian (1872 - 1944) fue parte de qué movimiento?', 'Neoplasticismo', 'Precisionismo', 'Cubismo', 'Impresionismo'),
(3, '¿Cuál es la palabra italiana para "tomate"?', 'Pomodoro', 'Aglio', 'Cipolla', 'Peperoncino'),
(3, '¿Cuál es la palabra francesa para "sombrero"?', 'Chapeau', 'Bonnet', 'Echarpe', 'Casque'),
(3, '¿Cuál es la palabra árabe romanizada para "luna"?', 'Qamar', 'Najma', 'Kawkab', 'Shams'),
(3, '¿Cuál es el sustantivo más utilizado en el idioma inglés?', '"Time"', '"Home"', '"Water"', '"Man"'),
(3, '¿Cuál es la palabra china romanizada para "avión"?', '"Feiji"', '"Qiche"', '"Zongxian"', '"Huojian"'),
(3, '¿Qué cóctel componen whisky escocés y Drambuie?', 'Rusty Nail', 'Screwdriver', 'Sex on the Beach', 'Manhattan'),
(4, 'En física cuántica ¿Cuál de estas partículas subatómicas teorizadas aún no se ha observado?', 'Gravitón', 'Gluón', 'Neutrino tau', 'bozón Z'),
(4, '¿Cuál es el color de la sangre no oxidada?', 'Rojo', 'Azul', 'Verde', 'Púrpura'),
(4, '¿Miopía es el término científico para qué condición?', 'Cortedad de alcances o de miras', 'Hipermetropía', 'Visión doble', 'Visión nublada'),
(4, '¿Entre qué dos planetas se encuentra el cinturón de asteroides?', 'Marte y Júpiter', 'Júpiter y Saturno', 'Mercurio y Venus', 'Tierra y Marte'),
(4, '¿Cuál de los siguientes es el término para complicaciones quirúrgicas resultantes de esponjas quirúrgicas dejadas dentro del cuerpo del paciente?', 'Gossypiboma', 'Gongozler', 'Jentacular', 'Meupareunia'),
(4, '¿Qué unidad científica lleva el nombre de un noble italiano?', 'Voltio', 'Pascal', 'Ohm', 'Hercios'),
(4, '¿Qué elemento químico, el número 11 de la tabla periódica, tiene el símbolo Na?', 'Sodio', 'Carbono', 'Plomo', 'Nitrógeno'),
(4, '¿Qué causa el sonido de los latidos del corazón?', 'Cierre de las válvulas del corazón', 'Contracción de las cavidades del corazón', 'Sangre que sale del corazón', 'Relajación de las cámaras del corazón'),
(4, '¿Quién hizo el descubrimiento de los Rayos X?', 'Wilhelm Conrad Röntgen', 'Thomas Alva Edison', 'James Watt', 'Albert Einstein'),
(4, '¿El ácido fólico es la forma sintética de qué vitamina?', 'Vitamina B', 'Vitamina A', 'Vitamina C', 'Vitamina D'),
(4, '¿Cuál es el peso atómico estándar de un núcleo de plutonio?', '244', '94', '481', '128'),
(4, '¿La coulrofobia es el miedo irracional a qué?', 'Payasos', 'Cementerios', 'Agujas', 'Túneles'),
(4, 'En aeronáutica ¿Qué se utilizan los flaps y slats en un avión?', 'Levantamiento', 'Empuje', 'Arrastrar', 'Peso'),
(4, '¿Qué término se asocia mejor con Sigmund Freud?', 'Psicoanálisis', 'Cognitivo Terapia Conductual', 'Teoría de la Gravedad', 'Terapia Dialéctica Conductual'),
(4, '¿Cuánto mide un año luz?', '9,461 billones de kilómetros', '1 AU', '105,40 años terrestres', '501,2 millones de millas'),
(4, '¿Cuál es la fórmula molecular de la glucosa?', 'C6H12O6', 'C2H4O2', 'K+', 'CH4'),
(4, 'Al minuto más cercano ¿Cuánto tiempo tarda la velocidad de la luz en viajar desde el Sol a la Tierra?', '8 minutos', '6 minutos', '2 minutos', '12 minutos'),
(4, '¿La teoría del Big Bang" fue teorizada por primera vez por un sacerdote de qué ideología religiosa?', 'católica', 'cristiana', 'judía', 'islámica'),
(4, 'Si plantaras semillas de Quercus robur ¿Qué crecería?', 'Árboles', 'Flores', 'Verduras', 'Granos'),
(4, '¿Qué significa ADN?', 'Ácido desoxirribonucleico', 'Ácido desoxirribogenético', 'Átomos desoxirribogenéticos', 'Ácido detóxico'),
(4, 'En física, la conservación de la energía y la conservación del impulso son consecuencias de:', 'Teorema de Noether', 'Teorema de Bell', 'Teorema de Wick', 'Teorema de Carnot'),
(4, 'En el plano complejo, multiplicar una función dada por i la gira en sentido antihorario ¿Cuántos grados?', '90', '270', '180', '0'),
(4, '¿Cuál de los siguientes matemáticos hizo contribuciones importantes a la teoría de juegos?', 'John Von Neumann', 'Carl Friedrich Gauss', 'Leonhard Euler', 'Stefan Banach'),
(4, '¿Qué sería el número decimal 31 en hexadecimal?', '1F', '3D', '2E', '1B'),
(4, '¿Cuántos lados tiene un trapecio?', '4', '3', '5', '6'),
(4, '¿"La noción de un conjunto que contiene todos los conjuntos que no se contienen a sí mismos" es una idea paradójica atribuida a qué filósofo inglés?', 'Bertrand Russel', 'Francis Bacon', 'John Locke', 'Alfred North Whitehead'),
(4, '¿Cuál de las siguientes empresas de dispositivos móviles NO tiene su sede en Asia?', 'Nokia', 'LG Electronics', 'Samsung', 'HTC'),
(4, '¿Qué bala dispara un M1 Garand de la Segunda Guerra Mundial?', '.30-06', '.308', '7.62', '7.62x51mm'),
(4, '¿Las impresoras láser y de inyección de tinta son ejemplos de qué tipo de impresora?', 'Impresora sin impacto', 'Impresora de impacto', 'Impresora matricial de puntos', 'Impresora tipo margarita'),
(4, '¿Qué palabra de cinco letras es el lema de la compañía IBM Computer?', 'Think (Pensar)', 'Click', 'Logic (Lógica)', 'Pixel'),
(4, '¿Cuál de estos era el nombre de un error encontrado en abril de 2014 en la biblioteca de criptografía OpenSSL disponible públicamente?', 'Heartbleed', 'Shellshock', 'Corrupted Blood', 'Shellscript'),
(4, '¿Cuál de estas personas NO fue fundador de Apple Inc?', 'Jonathan Ive', 'Steve Jobs', 'Ronald Wayne', 'Steve Wozniak'),
(4, '¿Cuál fue la primera empresa en utilizar el término "Golden Master"?', 'Apple', 'IBM', 'Microsoft', 'Google'),
(4, 'En el lenguaje de programación "Python" ¿Cuál de estas declaraciones mostraría la cadena "Hola mundo" correctamente?', 'print("Hola mundo")', 'console.log("Hola mundo")', 'echo "Hola mundo"', 'printf("Hola mundo")'),
(4, 'El sistema de numeración con una base de 16 se conoce más comúnmente como:', 'Hexadecimal', 'Binario', 'Duodecimal', 'Octal'),
(4, '¿Qué significa LTS en el mercado de software?', 'Long Term Support', 'Long Taco Service', 'Ludicrous Transfer Speed', 'Ludicrous Turbo Speed'),
(4, 'En "Hexadecimal" ¿Qué color se mostraría en el código de color "#00FF00"?', 'Verde', 'Rojo', 'Azul', 'Amarillo'),
(4, '¿El científico informático holandés Mark Overmars es conocido por crear qué motor de desarrollo de juegos?', 'Game Maker', 'Stencyl', 'Construct', 'Torque 2D'),
(5, '¿Por qué evento trágico se recuerda la temporada de F1 de 1994?', 'Muerte de Ayrton Senna (San Marino)', 'The Showdown (Australia)', 'Verstappen on Fire (Alemania)', 'La prohibición de Schumacher (Gran Bretaña)'),
(5, '¿De qué país se originó el Kabaddi (deporte de contacto que implica placajes)?', 'India', 'Australia', 'Turquía', 'Camboya'),
(5, '¿Qué término de críquet denota que un bateador es despedido con una puntuación de cero?', 'Duck', 'Bye', 'Beamer', 'Carry'),
(5, '¿A qué equipo venció a Inglaterra en las semifinales para ganar la final del Mundial de 1966?', 'Portugal', 'Alemania Occidental', 'Unión Soviética', 'Brasil'),
(5, '¿Cuál es la longitud exacta de una parte no curva en el carril 1 de una pista olímpica?', '84,39m', '100 metros', '100 yardas', '109,36 yardas'),
(5, '¿Quién ganó el Campeonato Mundial de Pilotos de Fórmula 1 2016?', 'Nico Rosberg', 'Lewis Hamilton', 'Max Verstappen', 'Kimi Raikkonen'),
(5, '¿Cuál es el nombre completo del futbolista "Cristiano Ronaldo"?', 'Cristiano Ronaldo dos Santos Aveiro', 'Cristiano Ronaldo los Santos Diego', 'Cristiano Armando Diego Ronaldo', 'Cristiano Luis Armando Ronaldo'),
(5, '¿El logotipo de qué empresa alemana de ropa deportiva es "Formstripe"?', 'Puma', 'Nike', 'Adidas', 'Reebok'),
(5, '¿Quién ganó la UEFA Champions League en 2016?', 'Real Madrid CF', 'FC Bayern Munich', 'Atlético de Madrid', 'Manchester City FC'),
(5, '¿Quién ganó el Campeonato Mundial de Fórmula 1 2015?', 'Lewis Hamilton', 'Nico Rosberg', 'Sebastian Vettel', 'Jenson Button'),
(5, '¿En qué fecha se celebró la ceremonia de clausura de los Juegos Olímpicos de Verano de Río 2016?', '21 de agosto', '23 de agosto', '19 de agosto', '17 de agosto'),
(5, '¿Qué equipo de fútbol inglés recibe el sobrenombre de "Los Tigres"?', 'Ciudad Casco', 'Cardiff City', 'Ciudad de Bristol', 'Ciudad de Manchester'),
(6, '¿Qué empresa desarrolló el videojuego "Borderlands"?', 'Gearbox Software', 'Activision', '2K Games', 'Rockstar Games'),
(6, '¿Qué refugio del videojuego "Fallout 3" es el hogar de varios clones llamados Gary?', 'Refugio 108', 'Refugio 101', 'Refugio 87', 'Refugio 21'),
(6, '¿Quién hizo el mod de Garry?', 'Garry Newman', 'Gabe Newell', 'Randy Newman', 'Facepunch Studios'),
(6, 'Si juegas Super Mario RPG y tomas una siesta en una habitación de hotel alquilada ¿Te despertarás junto a qué personaje de aspecto familiar?', 'Link', 'Wario', 'Samus', 'Q*bert'),
(6, '¿Qué día en "Papers, Please" Aparece el hombre de rojo?', 'Día 23', 'Día 20', 'Día 17', 'Día 15'),
(6, '¿De qué nacionalidad es D.Va de Overwatch?', 'Coreana', 'China', 'Japonés', 'Vietnamita'),
(6, '¿Cuál fue el primer videojuego producido por la empresa desarrolladora Rare?', 'Slalom', 'R.C. Pro-Am', 'Battletoads', 'Donkey Kong Country'),
(6, 'En Pokémon ¿Cuál es la habilidad oculta de Palkia?', 'Telepatía', 'Presión', 'Hidratación', 'Burbuja de agua'),
(6, '¿Cuál es el título del protagonista que le dan los demonios en DOOM (2016)?', 'Doom Slayer', 'Doom Guy', 'Doom Marine', 'Doom Reaper'),
(6, '¿Qué personaje de "Touhou Project" tuvo su primera aparición como jefe intermedio en el octavo juego, "Imperishable Night"?', 'Tewi Inaba', 'Mystia Lorelei', 'Kaguya Houraisan', 'Rumia'),
(6, '¿Cuánto cuesta el "AWP" en Counter-Strike: Global Offensive?', '$4750', '$4500', '$4650', '$5000'),
(6, 'En Call Of Duty: Black Ops II ¿Quién es el principal antagonista?', 'Raul Menéndez', 'Vladimir Makarov', 'Frank Woods', 'DeFalco'),
(6, '¿Cuál de estos no es un vehículo DLC en "Mario Kart 8"?', 'Wild Wiggler', 'Bone Rattler', 'B Dasher', '300 SL Roadster'),
(6, 'En "Call Of Duty: Zombies" ¿Qué mapa muestra la escena de apertura en donde "Richtofen" mata a otra versión de sí mismo?', 'The Giant', 'Shadows Of Evil', 'Der Eisendrache', 'Moon'),
(6, 'En la serie Animal Crossing ¿Qué flor se llama erróneamente "La Escalera de Jacob"?', 'Lirio de los valles', 'Hortensia', 'Campánula', 'Milenrama'),
(6, '¿Quién es el líder del Equipo Instinto en Pokémon Go?', 'Spark', 'Candela', 'Blanche', 'Willow'),
(6, 'En World of Warcraft ¿Cuál es el color predeterminado de la interfaz de usuario que significa druida?', 'Naranja', 'Marrón', 'Verde', 'Azul'),
(6, 'En "Call of Duty: Black Ops III" Zombies ¿Con qué te recompensa completar todos los huevos de Pascua principales?', '1,000,000 XP', 'Juggernog al inicio de cada juego', '50 Liquid Diviniums', 'Las tres opciones'),
(6, '¿Cuál es la primera consola de videojuegos del mundo?', 'Magnavox Odyssey', 'Coleco Telstar', 'Nintendo Color TV Game', 'Atari 2600'),
(6, '¿Quién fue el primer jedi que Starkiller tuvo que matar en "Star Wars: The Force Unleashed"?', 'Rahm Kota', 'Ahsoka Tano', 'Kazdan Paratus', 'Kento Marek'),
(6, 'En "Call Of Duty: Zombies" ¿Qué recompensa se otorga tradicionalmente por completar una ronda de jefe?', 'Munición máxima', 'Un arma Pack-A-Punched', 'Death Machine', 'Monkey Bombs'),
(6, '¿En qué planeta se desarrolla el juego Freedom Planet (2014)?', 'Avalice', 'Freedom', 'Galaxytrail', 'Shang Mu'),
(6, '¿Cuándo se lanzó Minecraft al público por primera vez?', '17 de mayo de 2009', '17 de septiembre de 2009', '18 de noviembre de 2011', '7 de octubre de 2011'),
(6, '¿Cómo se llamaba el cancelado proyectado por Blizzard Entertainment que luego se convertiría en Overwatch?', 'Titan', 'Omnic', 'Omega', 'Ghost'),
(6, '¿En qué planeta se desarrolla el juego Freedom Planet (2014)?', 'Avalice', 'Freedom', 'Galaxytrail', 'Shang Mu'),
(6, '¿Cuál de estas armas NO está disponible para el equipo terrorista en el juego "Counter-Strike: Global Offensive"?', 'SCAR-20', 'SG 550', 'CZ-75', 'XM1014'),
(6, '¿De qué país era Eliza "Ash" Cohen de "Tom Clancy Rainbow Six Siege"?', 'Israel', 'Estados Unidos', 'México', 'Canadá'),
(6, 'En la serie PAYDAY ¿Quién es el líder icónico de la pandilla PAYDAY?', 'Dallas', 'Wolf', 'Chains', 'Hoxton'),
(6, 'En Call of Duty: Zombies ¿Cómo se llama la ballesta Pack-A-Punched?', 'Awful Lawton', 'Longinus', 'V-R11', 'Predator'),
(6, '¿Cuál de los siguientes juegos de Call of Duty fue un título de lanzamiento de PS3?', 'Call of Duty 3', 'Call of Duty 4: Modern Warfare', 'Call of Duty: World at War', 'Call of Duty: Roads to Victory'),
(6, '¿Dónde tiene lugar "The Legend of Zelda: Majora Mask"?', 'Termina', 'Hyrule', 'Gysahl', 'Besaid'),
(6, '¿Qué franquicia tiene la criatura "Slowpoke"?', 'Pokemon', 'Dragon Ball', 'Sonic The Hedgehog', 'Yu Gi Oh'),
(6, '¿En qué se inspiró la colección de juegos de navegador "Kantai"?', 'En la Segunda Guerra Mundial', 'En un Manga', 'En World of Warcraft', 'En un Anime'),
(6, '¿Qué miembro de Monty Python interpretó a Rincewind del juego "Discworld" de 1995?', 'Eric Idle', 'John Cleese', 'Terry Gilliam', 'Michael Palin'),
(6, '¿Cuál es el nombre de la empresa en Lethal Company?', 'The Company', 'Planet Scrap Co.', 'Lethal Robotics', 'Gordian Shipping Co.'),
(6, '¿Qué personaje tuvo su primera aparición en Touhou Project como jefe intermedio en el octavo juego, "Imperishable Night?"', 'Tewi Inaba', 'Mystia Lorelei', 'Kaguya Houraisan', 'Rumia'),
(6, '¿Cuál es el nombre del primer jefe que el jugador se encuentra en el juego de 2017, "Little Nightmares"?', 'The Janitor', 'The Warden', 'The Caretaker', 'The Overseer'),
(6, '¿Cuándo se lanzó Pokémon GO en Norteamérica?', '6 de julio de 2016', '5 de junio de 2016', '24 de mayo de 2016', '2 de enero de 2017'),
(6, '¿Cuál era el apodo del modelo original del protagonista de Half-Life, Gordon Freeman?', 'Ivan the Space Biker', 'Gordon the Space Biker', 'Ivan the Alien Biker', 'Gordon the Alien Biker'),
(6, '¿Cuál de los siguientes personajes no forma parte de la serie de juegos Street Fighter?', 'Mai Shiranui', 'Laura Matsuda', 'Sakura Kasugano', 'Ibuki'),
(6, 'En "Sonic the Hedgehog 2" para Sega Genesis ¿Qué ingresas en la pantalla de prueba de sonido para acceder a la selección de nivel secreto?', 'El cumpleaños del programador principal', 'La primera fecha de lanzamiento de "Sonic the Hedgehog"', 'La fecha en que se fundó Sonic Team', 'La primera fecha de lanzamiento de "Sonic the Hedgehog 2"'),
(6, 'En "Call Of Duty: Zombies", completar el huevo de Pascua ¿Qué mapa te recompensará con el logro "El viaje en el tiempo Tell"??', 'Shangri-La', 'Ascensión', 'Luna', 'Die Rise'),
(6, 'En "Starbound" ¿Cuál es el HP máximo del monstruo "Punchy"?', '50,000 HP', '9,000,000 HP', '100 HP', '150.000 HP'),
(6, 'El juego gráficamente más violento que precede a la creación de la ESRB (Entertainment Software Rating Board) era...', 'Mortal Kombat', 'Duke Nukem', 'Resident Evil', 'Doom'),
(6, '¿Quién compuso el banda sonora del juego "VVVVVV"?', 'Magnus Pålsson', 'Terry Cavanagh', 'Danny Baranowsky', 'Joel Zimmerman'),
(6, '¿Cuál es el nombre de la isla principal en "PLAYERUNKNOWN´S BATTLEGROUNDS"?', 'Erangel', 'Marmara', 'Severny', 'Lastovo'),
(6, 'En Geometry Dash ¿Qué canción es el nivel 13?', 'Electroman Adventures', 'Theory of Everything', 'Clubstep', 'Clutterfunk'),
(6, '¿Cuál es el alias predeterminado que utiliza la Princesa Garnet en Final Fantasy IX?', 'Dagger', 'Dirk', 'Granate', 'Quina'),
(6, '¿En qué año se lanzó el primer juego de Monster Hunter?', '2004', '2006', '2005', '2002'),
(6, '¿Qué videojuego fue retirado del mercado por tener escondido un episodio reproducible de South Park?', 'Tiger Woods 99 PGA Tour', 'Tony Hawk´s Pro Skater 3', 'Sonic Adventure', 'Madden 99'),
(6, '¿Cuál de los siguientes personajes es del videojuego Destiny?', 'Cayde-6', 'Ostrava of Boletaria', 'Mordecai the Hunter', 'Leon S. Kennedy'),
(6, '¿Cuál de estos personajes casi se agregó a Super Smash Bros. Melee, pero no se incluyó porque el juego estaba demasiado desarrollado?', 'Solid Snake', 'Pit', 'Meta Knight', 'R.O.B.'),
(6, 'En "PAYDAY 2" ¿Qué arma tiene el mayor daño base por disparo?', 'HRL-7', 'Ballesta pesada', 'Thanatos .50 cal', 'Pistola Broomstick'),
(6, '¿Cuál de los siguientes bojetos de Mario Kart 8 Deluxe NO te harán invencible?', 'Hongo dorado', 'Estrella', 'Bill Bala', 'Boo'),
(6, '¿En qué año se lanzó el juego "Eliminator"?', '1998', '2000', '1999', '2001'),
(6, 'En "The Binding of Isaac" ¿Cómo se llama el jefe final con el que luchas en The Void?', 'Delirium', 'Mega Satan', 'Hush', 'The Lamb'),
(6, '¿Qué nivel mínimo en la habilidad de Defensa se necesita para equipar Dragon Armor en el MMO "RuneScape"?', '60', '65', '55', '70'),
(6, '¿Cuándo se lanzó Club Penguin?', '24 de octubre de 2005', '21 de octubre de 2005', '29 de marzo de 2006', '22 de noviembre de 2004'),
(6, '¿Cuál es el nombre de la personaje principal de "Life is Strange"?', 'Maxine Caulfield', 'Victoria Chase', 'Stella Hill', 'Chloe Price'),
(6, 'El icono de "Tomb Raider" Lara Croft se llamaba originalmente...', 'Laura Cruz', 'Laura Craft', 'Laura Croft', 'Lara Craft'),
(6, '¿Qué operación en "Tom Clancy´s Rainbow Six Siege" introdujo el mapa "Skyscraper"', 'Red Crow', 'Velvet Shell', 'Skull Rain', 'Dust Line'),
(6, 'En el trailer "Meet the Heavy" de Team Fortress 2 ¿Qué nombre le pusó Heavy a su minigun?', 'Sasha', 'Betty', 'Anna', 'Diana'),
(6, '¿Cómo se llama tu equipo en Star Wars: Republic Commando?', 'Escuadrón Delta', 'Los Comandos', 'Bravo Seis', 'El Puño de Vader'),
(6, 'En "Pokémon Sol y Luna" ¿De qué ciudad el Equipo Skull se hizo cargo?', 'Pueblo Po', 'Ciudad Heahea', 'Aldea Tanu', 'Pueblo Iki'),
(6, '¿Dónde se encuentra más comúnmente los "Terror Fiends" en el juego de Nintendo Miitopia?', 'New Lumos', 'Peculia', 'The Sky Scraper', 'Otherworld'),
(6, 'En Super Smash Bros 3DS/Wii U ¿Qué personaje veterano fue el primero en regresar después de estar ausente en el juego anterior?', 'Dr. Mario', 'Mewtwo', 'Lucas', 'Roy'),
(6, '¿Qué bloque de Minecraft tiene la mayor resistencia a las explosiones?', 'Bloque de barrera', 'Obsidiana', 'Bedrock', 'Bloque de diamante'),
(6, '¿Cuál de estos motores de videojuegos fue creado por la empresa Epic Games?', 'Unreal', 'Unity', 'Game Maker: Studio', 'Cry Engine'),
(6, 'El CEO de Aperture Science, Cave Johnson ¿Qué actor estadounidense le da voz?', 'JK Simmons', 'Nolan North', 'John Patrick Lowrie', 'Christopher Lloyd'),
(6, '¿Cuál de los siguientes no es un personaje del videojuego "Doki Doki Literature Club"?', 'Nico', 'Monika', 'Natsuki', 'Sayori'),
(6, '¿Cuándo fue publicado el juego "Portal 2"?', '2011', '2014', '2009', '2007'),
(6, '¿Quién creó el videojuego de 2011 "Minecraft"?', 'Markus Persson', 'Jens Bergensten', 'Daniel Rosenfeld', 'Carl Manneh'),
(6, 'En el juego Danganronpa: Happy Trigger Havoc ¿Cuál es la habilidad definitiva del personaje Aoi Asahina?', 'Nadadora definitiva', 'Detective definitiva', 'Apostadora definitiva', 'Bailarina definitiva'),
(6, 'En la mayoría de los videojuegos FPS como Counter-Strike ¿A qué parte del cuerpo causa el mayor daño al dispararle?', 'Cabeza', 'Brazo', 'Pierna', 'Pecho'),
(6, 'En Kingdom Hearts ¿Cuál de los siguientes personajes no puede empuñar una llave espada?', 'Larxene', 'Xehanort', 'Lea', 'Mickey'),
(6, '¿Qué grupo interpreta la canción "Crash into Me"?', 'Dave Matthews Band', 'Phish', 'The Grateful Dead', 'Destiny´s Child'),
(6, '¿En qué año se agregaron capturas de pantalla a Steam?', '2011', '2010', '2008', '2009'),
(6, 'Rocket League es un juego que incluye...', 'Coches', 'Helicópteros', 'Aviones', 'Submarinos'),
(6, '¿Cuántas copias del famoso juego ET para Atari 2600 terminó vendiendo Atari?', '1,5 millones', '1 millón', '250 mil', 'Menos de 250 mil'),
(6, '¿De qué empresa compró Bethesda la serie Fallout?', 'Interplay Entertainment', 'Capcom', 'Blizzard ', 'Nintendo'),
(6, 'En Undertale ¿Cuánto cuestan los Spider Donuts en Hotland?', '9999G', '7G', '40G', '12G'),
(6, 'Antes de su aparición en Super Smash Bros Ultimate ¿Cuál fue la última aparición de King K. Rool en cualquier juego?', 'Mario Super Sluggers', 'Donkey Kong 64', 'Donkey Kong Country 3', 'Donkey Kong: Rey del swing'),
(6, '¿Quién es el creador de la serie Super Smash Bros?', 'Masahiro Sakurai', 'Reggie Fils-Aimé', 'Bill Trinen', 'Hideo Kojima'),
(6, '¿Cuál era el nombre en clave de "Nintendo Gamecube"?', 'Dolphin', 'Nitro', 'Revolution', 'Atlantis'),
(6, 'En el trailer de Team Fortress 2, "Meet The Spy" ¿Qué contraseña pone Soldier en teclado númerico de la puerta?', '1111', '1432', '1337', 'No hay contraseña'),
(6, '¿Quién le da voz a Max Payne en el juego de 2001 "Max Payne"?', 'James McCaffrey', 'Sam Lake', 'Troy Baker', 'Hideo Kojima'),
(6, '¿Cuál es el título de la canción en el menú principal de Halo?', 'Halo', 'Opening Suite', 'Shadows', 'Suite Otoño'),
(6, 'En la década de 1980, apareció un servicio llamado Gameline qu permitió a los usuarios descargar juegos de una consola ¿Cuál es?', 'Atari 2600', 'Sega Genesis', 'Nintendo Entertainment System', 'ColecoVision'),
(6, '¿Cómo se llama la armada comun de enemigos de la serie de videojuegos "Oddworld"?', 'Sligs', 'Scrabs', 'Slogs', 'Glukkons'),
(6, '¿Qué desventaja de Terraria el hechizo ankh no proporciona inmunidad?', 'Envenamiento', 'Maldición', 'Sangrado', 'Lentitud'),
(6, 'Durante el desarrollo de "Super Mario World" ¿Cuál de estas era originalmente la dura silla de Yoshi?', 'Un caparazón', 'Un portaobjetos de gelatina', 'Un frailecillo', 'Una púa'),
(6, 'La creación del ESRB (Entretenimiento La Junta de Clasificación de Software) se asocia a menudo con Mortal Kombat y a un videojuego FMV ¿Cuál es?', 'Night Trap', 'Sewer Shark', 'The Daedalus Encounter', 'Corpse Killer'),
(6, '¿Qué raza no es jugable en "Final Fantasy XIV: A Realm Reborn"?', 'Hume', 'Miqo´te', 'Lalafell', 'Roegadyn'),
(6, '¿Qué etapa estaba planeada para ser parte de "Sonic the Hedgehog 2" pero fue descartado durante el desarrollo?', 'Genocide City Zone', 'Stardust Speedway Zone', 'Sky High Zone', 'Clockwork Zone'),
(6, 'En el original "Super Mario Bros" ¿Cuál sería la aceleración de Mario si estuviera en caída libre?', '91.28 m/s^2', '110 m/s^2', '9,42 m/s^2', '4,4 m/s^2'),
(6, '¿Quién fue el principal antagonista de Max Payne 3 (2012)?', 'Victor Branco', 'Álvaro Neves', 'Armando Becker', 'Milo Rego'),
(6, '¿Qué tienen en común los videojuegos No Man´s Sky, Mighty No. 9, Mafia III y Street Fighter V?', 'Fueron considerados los peores juegos de 2016', 'Fueron financiados mediante crowdfunding', 'Fueron desarrollados por estudios independientes', 'Fueron lanzados para PlayStation 3'),
(6, '¿En qué año salió la primera versión de Blockland?', '2004', '2007', '2008', '2006'),
(6, 'Cryoshell, conocido por "Creeping in My Soul" ¿Para qué tema Lego hizo la música publicitaria?', 'Bionicle', 'Hero Factory', 'Star Wars', 'Ben 10 Alien Force'),
(6, '¿Cuándo lanzaron The Beatles el LP "Why Please Me"?', '1963', '1960', '1969', '1970'),
(6, '¿"The Gene" es el nombre original y secundario de qué miembro del Wu-Tang Clan?', 'GZA', 'Ghostface Killah', 'Ol Dirty Bastard', 'Raekwon the Chef'),
(6, '¿Cuál de estas canciones no es de Tatsuro Yamashita?', 'Lucky Lady Feel So Good', 'Merry-Go Round', 'Let Dance Baby', 'Love Talkin'),
(6, '¿Cuál era el primer album de Radiohead?', 'Pablo Honey', 'The Bends', 'Kid A', 'A Moon Shaped Pool'),
(6, '¿De qué ciudad inglesa proviene la banda de heavy metal "Black Sabbath"?', 'Birmingham', 'Manchester', 'Londres', 'Newcastle-Upon-Tyne'),
(6, '"Doctor Jones", "Turn Back Time" y "Barbie Girl" fueron los números uno en el Reino Unido ¿Qué grupo de Eurodance los creó?', 'Aqua', 'Vengaboys', 'Eiffel 65', 'Sash!'),
(6, '¿Pamina y Papageno son personajes de qué ópera de Mozart?', 'La Flauta Mágica', 'Las bodas de Fígaro', 'El empresario', 'El ganso de El Cairo'),
(6, '¿Qué guitarrista inglés tiene el apodo de "Slowhand"?', 'Eric Clapton', 'Mark Knopfler', 'Jeff Beck', 'Jimmy Page'),
(6, '¿Qué cantante apareció en la canción "Wake Me Up" del productor sueco Avicii?', 'Aloe Blacc', 'John Legend', 'CeeLo Green', 'Pharrell Williams'),
(6, '¿Cuál de los siguientes es un álbum de la banda de punk rock "Anti-Flag"?', 'For Blood And Empire', 'Infinity On High', '21st Century Breakdown', 'No Pads, No Helmets...Just Balls'),
(6, '¿Qué grupo de música electrónica fundó Liam Howlett en 1990?', 'The Prodigy', 'The Chemical Brothers', 'The Crystal Method', 'Infected Mushroom'),
(6, '¿Cómo se llamaba el cantante de la guerra fría que tiene una canción en GTA IV y un muro en Moscú para su homenaje?', 'Viktor Tsoi', 'Jimi Hendrix', 'Brian Jones', 'Vladimir Vysotsky'),
(6, '¿A qué fecha se hace referencia en la canción de 1971 "September" de Earth, Wind & Fire?', '21 de septiembre', '26 de septiembre', '23 de septiembre', '24 de septiembre'),
(6, '¿De cuál de las siguientes bandas no forma parte Tom DeLonge?', '+44', 'Box Car Racer', 'Blink-182', 'Angels & Airwaves'),
(6, '¿Cuáles de estos artistas NO son originarios de Francia?', 'The Chemical Brothers', 'Air', 'Justice', 'Daft Punk'),
(6, '¿De qué artista de música electrónica es el album "Drink the Sea"?', 'The Glitch Mob', 'Avicii', 'XXYYXX', 'Flux Pavilion'),
(6, '¿Cómo cuántos miembros hay en el grupo de idols "µ´s"?', '9', '48', '6', '3'),
(6, '¿Quién es el líder de Muse?', 'Matt Bellamy', 'Dominic Howard', 'Thom Yorke', 'Jonny Greenwood'),
(6, '¿Cuál fue el álbum debut solista de Raekwon the Chefs?', 'Only Built 4 Cuban Linx', 'Shaolin vs Wu-Tang', 'The Wild', 'The Lex Diamond Story'),
(6, 'Según la rapera estadounidense Nelly ¿Qué debes hacer cuando hace calor?', 'Quítate toda la ropa', 'Date una ducha fría', 'Bebe un poco de agua', 'Haz un baño desnudo'),
(6, 'El músico irlandés Hozier lanzó una canción en 2013 titulada "Take Me to ______"', 'Church', 'Mosque', 'Synagogue', 'Temple'),
(6, '¿Qué familia estadounidense La banda alcanzó el top 10 en 1986 con la canción "Crush On You"?', 'The Jets', 'DeBarge', 'The Jacksons', 'The Cover Girls'),
(6, '¿Cuál de los siguientes guitarristas grabó un álbum como miembro de los Red Hot Chili Peppers?', 'Dave Navarro', 'Tom Morello', 'Billy Corgan', 'Ed O´Brien'),
(6, '¿Cuántos álbumes de estudio ha lanzado el dúo Daft Punk?', '4', '1', '5', '2'),
(6, '¿Saul Hudson (Slash) de la banda "Guns N´ Roses" es conocido por tocar qué tipo de guitarra?', 'Les Paul Standard', 'Fender Stratocaster', 'LsL Mongrel', 'Gretsch Falcon'),
(6, '¿Qué canción interpretada originalmente por The Bee Gees en 1978 tuvo una versión de Steps 20 años después?', '"Tragedy"', '"Night Fever"', '"Stayin´ Alive"', '"You Should Be Dancing"'),
(6, '¿Quién es el fundador y líder de la banda de rock industrial "Nine Inch Nails"?', 'Trent Reznor', 'Marilyn Manson', 'Robin Finck', 'Josh Homme'),
(6, '¿Qué grupo de música electrónica en 1990 fundo Liam Howlett?', 'The Prodigy', 'The Chemical Brothers', 'The Crystal Method', 'Infected Mushroom'),
(6, 'La "K" en la palabra "K-Pop" ¿Qué significa?', 'Korean (Coreano)', 'Keniano', 'Kazajstán', 'Kuwaití'),
(6, '¿Cuáles de estas bandas NO son de Australia?', 'The Naked and Famous', 'Cut Copy', 'Empire of the Sun', 'Tame Impala'),
(6, '¿Quién es el cantante principal de Arctic Monkeys?', 'Alex Turner', 'Jamie Cook', 'Matt Helders', 'Nick O´Malley'),
(6, '¿En qué año se compuso la Obertura de 1812 de Tchaikovsky?', '1880', '1812', '1790', '1840'),
(6, '¿Cómo se llama el hit en solitario del DJ finlandés "Darude" lanzado en octubre de 1999?', 'Sandstorm', 'Dust Devil', 'Sirocco', 'Khamsin'),
(6, '¿Qué banda era mejor conocida por sus éxitos en las listas del Reino Unido "Combine Harvester" y "I Am a Cider Drinker" en 1976?', 'The Wurzels', 'Goldie Lookin Chain', 'Bonzo" Dog Doo-Dah Band', 'The Firm'),
(6, '¿The Proclaimers - I´m Gonna Be (500 Miles) a qué posición alcanzó en las listas Hot 100 de EE. UU. en 1993?', '3º', '8º', '1º', '5º'),
(6, 'En la serie Viernes 13 ¿Cuál es el nombre de pila de la madre de Jason?', 'Pamela', 'María', 'Cristina', 'Angelina'),
(6, 'Cuál jugador de fútbol americano quarterback retirado actuó de si mismo en "Ace Ventura: Detective de Mascotas" y en "Little Nicky"', 'Dan Marino', 'John Elway', 'Tom Brady', 'Joe Montana'),
(6, 'Al final de la película de 2001 "Rat Race" ¿En qué concierto se estrellan los concursantes?', 'Smash Mouth', 'Sum 41', 'Linkin Park', 'Bowling for Soup'),
(6, '¿Qué tres películas (en orden de fecha de estreno) componen la "Trilogía del Dólar"?', '"Por un Puñado de Dólares", "Por unos Dólares Más" y "El Bueno, El Malo y El Feo"', '"El Bueno, El Malo y El Feo", "Por Unos Pocos Dólares Más”, “Un Puñado de Dólares”', '"Por unos Dólares Más”, “El Bueno, El Malo y El Feo” y “Un Puñado de Dólares”', '"Por unos Dólares Más", "Un Puñado de Dólares" y "El Bueno, El Malo y El Feo"'),
(6, '¿Quién interpretó a Bruce Wayne/Batman en la película de 1989 de Tim Burton, "Batman"?', 'Michael Keaton', 'George Clooney', 'Val Kilmer', 'Adam West'),
(6, '¿Qué película de 1958 protagonizó a Kirk Douglas y Tony Curtis como los medio hermanos Einar y Eric?', 'Los Vikingos', 'Los barcos largos', 'Príncipe Valiente', 'Spartacus'),
(6, '¿Cuál es la ortografía correcta del protagonista del libro de La historia interminable (1984)?', 'Atreyu ', 'Atrayu', 'Atraiyu', 'Atraeyu'),
(6, 'En la película de Super Mario Bros (2023) ¿Quién interpreta a Toad?', 'Keegan-Michael Key', 'Seth Rogan', 'Charlie Day', 'Jack Black'),
(6, '¿Quién interpretó el tema de apertura de la película de James Bond 007 "Goldfinger"?', 'Shirley Basey', 'Tom Jones', 'John Barry', 'Sheena Easton'),
(6, '¿En qué película se incluye la canción de Micheal Jackson "Will You Be There"?', 'Free Willy', 'Sleepless in Seattle', 'Men in Black', 'Bad Boy'),
(6, 'En la película "Harry Potter y la Orden del Fénix" ¿Por qué el grito de Harry Potter, después de la muerte de Sirius Black, fue silenciado?', 'Por ser demasiado agonizante', 'Por ser demasiado fuerte', 'Por ser demasiado duro', 'Por ser demasiado violento'),
(6, '¿Cuál fue la última película de los hermanos Marx en la que apareció Zeppo?', 'Sopa de Ganso', 'Una noche en la ópera', 'Un día en las carreras', 'Mono Negocios'),
(6, '¿Qué cantante interpreta Bruce Campbell en la película de 2002 "Bubba Ho-Tep"', 'Elvis Presley', 'Johnny Cash', 'Hank Williams, Sr.', 'Buddy Holly'),
(6, '¿Cuál de los siguientes actores no desempeña un papel en la película "Los Sospechosos de Siempre"?', 'Steve Buscemi', 'Kevin Spacey', 'Benicio Del Toro', 'Gabriel Byrne'),
(6, '¿Cómo se llama el robot naranja y blanco de "Star Wars: El despertar de la fuerza"?', 'BB-8', 'BB-3', 'AA-A', 'R2-D2'),
(6, '¿Dónde se desarrolla la película original Viernes 13?', 'Camp Crystal Lake', 'Packanack', 'Higgins Haven', 'Camp Forest Green'),
(6, 'En la película "Blade Runner" ¿Cuál es el término utilizado para los androides con apariencia humana?', 'Replicants', 'Cylons', 'Synthetics', 'Skinjobs'),
(6, '¿Quién es el director de la película de 1991 "El silencio de los corderos"?', 'Jonathan Demme', 'Stanley Kubrick', 'Frank Darabont', 'Michael Bay'),
(6, 'En "Indiana Jones y el Templo de la Perdición" ¿De qué estaba hecho el "helado de sesos de mono"?', 'Natillas y salsa de frambuesa', 'Helado de fresa', 'Yogur de cereza', 'Sorbete de frambuesa'),
(6, '¿Cuál de las siguientes películas NO es una adaptación a las novela de Stephen King?', 'La Cosa', 'Carrie', 'Misery', 'La Milla Verde'),
(6, '¿Qué ciudad atacó el monstruo en la película "Cloverfield"?', 'Nueva York, Nueva York', 'Las Vegas, Nevada', 'Chicago, Illinois', 'Orlando, Florida'),
(6, 'La famosa revelación de Darth Vader a Luke es icónica ¿Pero cuál de estas es la correcta?', '"No. Yo soy tu padre."', '"Luke, soy tu padre"', '"Te equivocas. Soy tu padre"', '"La verdad es que soy tu padre"'),
(6, '¿Quién expresó el personaje de Draco en la película de 1996 "DragonHeart"?', 'Sean Connery', 'Dennis Quaid', 'Pete Postlethwaite', 'Brian Thompson'),
(6, '¿En qué año Clint Eastwood interpretó al inspector Harry Callahan en la película "Harry El Sucio"?', '1971', '1975', '1983', '1969'),

(6, '¿Quién escribió el cuento infantil "La niña de los fósforos"?', 'Hans Christian Andersen', 'Lewis Carroll', 'Charles Dickens', 'Oscar Wilde'),
(6, '¿Cuál es el nombre de la pandilla de la que Ponyboy forma parte en el libro "The Outsiders"?', 'The Greasers', 'The Mafia', 'The Socs', 'The Outsiders'),
(6, '¿Qué autor estadounidense fue también un escritor de viajes en ciernes y escribió de sus aventuras con su perro Charley?', 'John Steinbeck', 'F. Scott Fitzgerald', 'Ernest Hemingway', 'William Faulkner'),
(6, '¿Cuál es la marca y el modelo de los vehículos turísticos de "Jurassic Park" (1990)?', 'Toyota Land Cruiser 1989', 'Mercedes Clase M', 'Ford Explorer XLT 1989', 'Jeep Wrangler YJ Sahar 1989'),
(6, '¿Quién escribió la novela para jóvenes adultos "Bajo la misma estrella"?', 'John Green', 'Stephenie Meyer', 'Suzanne Collins', 'Stephen Chbosky'),
(6, '¿Cuál de los siguientes fue el autor de "Username Evie"?', 'Joe Sugg', 'Zoe Sugg', 'Joe Weller', 'Alfie Deyes'),
(6, '¿Cuál fue el último mensaje de los Delfines en "La Guía del autoestopista galáctico"?', '"Hasta luego y gracias por todos los peces"', '"La respuesta es 42."', '"Tierra de valientes"', '"¡Adiós mundo cruel!"'),
(6, '¿Cuál NO es un libro de la serie de Harry Potter?', 'El elfo doméstico', 'La Cámara de los Secretos', 'El Prisionero de Azkaban', 'Las Reliquias de la Muerte'),
(6, 'En El Señor de los Anillos ¿Quién es el padre del enano Gimli?', 'Gloin', 'Thorin Oakenshield', 'Bombur', 'Dwalin'),
(6, '¿Quién es el autor de la serie "Malaz: El libro de los caídos"?"', 'Steven Erikson', 'Ian Cameron Esslemont', 'George RR Martin', 'JRR Tolkien'),
(6, '¿Quién escribió la novela "Moby- Dick"?', 'Herman Melville', 'William Golding', 'William Shakespeare', 'JRR Tolkien'),
(6, '¿Qué autora escribió la novela "Jane Eyre"?', 'Charlotte Brontë', 'Emily Brontë', 'Jane Austen', 'Louisa May Alcott'),
(6, '¿Cómo se llama el dragón de Eragon en "Eragon"?', 'Saphira', 'Glaedr', 'Thorn', 'Arya'),
(6, 'En Alicia en el país de las maravillas ¿Cómo se llama el gatito de Alicia?', 'Dinah', 'Oscar', 'Heath', 'Smokey'),
(6, '¿Quién es el autor de Jurrasic Park?', 'Michael Crichton', 'Peter Benchley', 'Chuck Paluhniuk', 'Irvine Welsh'),
(6, '¿Cuál era el seudónimo de la novelista Mary Ann Evans?', 'George Eliot', 'George Orwell', 'George Bernard Shaw', 'George Saunders'),
(6, '¿En qué año se lanzó por primera vez "JoJo Bizarre Adventure: Phantom Blood"?', '1987', '1983', '1995', '2013'),
(6, 'En la versión "Re:Zero" serie manga ¿Cuál de los siguientes Arzobispos del Pecado se come la existencia de Rem?', 'Ley Batenkaitos', 'Roy Alphard', 'Petelgeuse Romanee-Conti', 'Louis Arneb'),
(6, '¿Qué canción suena en los créditos finales del anime "Ergo Proxy"?', 'Paranoid Android', 'Sadistic Summer', 'Bittersweet Symphony', 'Mad World'),
(6, 'En "To Love-Ru" ¿Quién es el primero en enterarse del pasado de Yami a través de ella?', 'Rito', 'Mikán', 'Lalá', 'Haruna'),
(6, '¿Quién es el titán blindado en "Attack On Titan"?', 'Reiner Braun', 'Armin Arlelt', 'Mikasa Ackermann', 'Eren Jaeger'),
(6, 'En "Hunter x Hunter" ¿Qué son los miembros de la familia de Killua conocidos por ser?', 'Assassins', 'Bandits', 'Hunters', 'Ninjas'),
(6, 'En la película animada de 2012 "Wolf Children" ¿Cuáles son los nombres de los niños lobo?', 'Ame & Yuki"', 'Hana & Yuki', 'Ame & Hana', 'Chuck & Anna'),
(6, '¿Qué parte del manga de JoJo´s Bizarre Adventure trata sobre una carrera de caballos por Estados Unidos?', 'Parte 7: Steel Ball Run', 'Parte 6: Stone Ocean', 'Parte 3: Stardust Crusaders', 'Parte 5: Golden Wind'),
(6, '¿A quién se le dio el título "Full Metal" en la serie de anime "Full Metal Alchemist"?', 'Edward Elric', 'Alphonse Elric', 'Van Hohenheim', 'Izumi Curtis'),
(6, '¿Quién es la verdadera princesa de la luna en Sailor Moon?', 'Sailor Moon', 'Sailor Venus', 'Sailor Mars', 'Sailor Jupiter'),
(6, '¿Cuál de estos títulos de manga no fue creado por Urasawa Naoki?', 'My Father´s Journal', 'Billy Bat', '20th Century Boys', 'Monster'),
(6, '¿Qué canción era el indicativo de la estación de radio KWFM de Stefan Verdemann en "Monster" de Urasawa Naoki?', 'Over the Rainbow', 'What a Wonderful World', 'When You Wish Upon A Star', 'Singing In The Rain'),
(6, '¿Cuál de los siguientes manga tiene más volúmenes tankouban?', 'Golgo 13', 'JoJo´s Bizarre Adventure', 'Detective Conan', 'One Piece'),
(6, '¿Cuál es el nombre del personaje principal del anime "One-Punch Man"?', 'Saitama', 'Genos', 'Sonic', 'King'),
(6, 'En "One Piece" ¿Quién es la chica que superó su pasado esclavizado y se convirtió en agente de un ejército para luchar contra el gobierno corrupto?', 'Koala', 'Boa Hancock', 'Nico Robin', 'Emporio Ivankov'),
(6, '¿Quién da voz al personaje "Reigen" en el doblaje en inglés de "Mob Psycho 100"?', 'Chris Niosi', 'Max Mittelman', 'Kyle McCarley', 'Casey Mongillo'),

(6, '¿Cuál es el nombre del Dr. Doofenshmirtz?', 'Heinz', 'Hans', 'Hank', 'Heidi'),
(6, '¿Cuál fue la primera palabra canónica de Maggie Simpson, sin incluir los cortos de Tracey Ullman?', 'Papá', '¡Ja!', '¡Rusty!', '¿Secuela?'),
(6, 'En "Los Simpson" ¿En dónde se conocieron Homero y Marge?', 'En el campamento de verano', 'En la escuela secundaria', 'En la iglesia', 'En 742 Evergreen Terrace'),
(6, 'En "El Asombroso Mundo de Gumball" ¿Quién es el director de Elmore Junior High?', 'Director Brown', 'Director Small', 'Director Brawn', 'Director Simeon'),
(6, 'En "Avatar: The Last Airbender" ¿Qué elemento comienza a aprender Aang después de ser descongelado?', 'Agua', 'Aire', 'Tierra', 'Fuego'),
(6, '¿Por qué vende Bart su alma en el episodio de Los Simpson "Bart vende su alma"?', '$5', 'Una copia de Bonestorm 2', '$100', 'Un Gobstopper gigante'),
(6, '¿Cuál es el nombre de la escuela en el anime y manga "Gosick"?', 'St. Marguerite', 'St. Augustine', 'St. Mary', 'St. Bernadette'),
(6, '¿Cómo se llamaba el oficial de policía en la caricatura "Top Cat"?', 'Dibble', 'Barbrady', 'Mahoney', 'Murphy'),
(6, '¿Qué habilidad tiene la Princesa Sofía Primera gracias a su amuleto que le permite respirar bajo el agua?', 'Transformación de sirena', 'Branquias artificiales', 'Cabeza de burbuja', 'Escudo de burbuja'),
(6, '¿Quién creó la serie de Cartoon Network "Hora de aventuras"?', 'Pendleton Ward', 'J. G. Quintel', 'Ben Bocquelet', 'Rebecca Sugar'),
(6, '¿En qué año se estrenó la película de Disney "A Goofy Movie"?', '1995', '1999', '2001', '1997'),
(6, '¿Cuál de las siguientes personas creó el programa de comedia stop motion "Pollo Robot"?', 'Seth Green', 'Seth MacFarlane', 'Seth Rogen', 'Seth Rollins'),
(6, '¿Cómo se conoce en Alemania al personaje de dibujos animados Andy Capp?', 'Willi Wakker', 'Dick Tingeler', 'Helmut Schmacker', 'Rod Tapper'),
(6, '¿Qué personaje de "Padre de familia" obtuvo su propio programa derivado en 2009?', 'Cleveland Brown', 'Glenn Quagmire', 'Joe Swanson', 'The Greased-up Deaf Guy'),

(6, '¿En qué año se lanzó el juego de mesa "Nightmare"?', '1991', '1992', '1989', '1995'),
(6, 'En Ajedrez ¿La Reina tiene el movimiento combinado con cuáles dos piezas?', 'Alfil y Torre', 'Torre y Rey', 'Caballero y Alfil', 'Rey y Caballero'),
(6, '¿Cuál de los siguientes juegos de mesa es el más antiguo?', 'Go', 'Ajedrez', 'Mahjong', 'Shogi'),
(6, '¿Cuántos dados se usan en el juego de Yahtzee?', 'Cinco', 'Cuatro', 'Seis', 'Ocho'),
(6, '¿Cuál era el nombre clave de desarrollo de la expansión "Urza´s Destiny" para "Magic: The Gathering", lanzada en 1999?', 'Chimichanga', 'Burrito', 'Taquito', 'Enchilada'),
(6, 'Al comienzo de un juego estándar del Monopoly, si lanzas un doble seis ¿En qué casilla caerías?', 'Compañía Eléctrica', 'Obras hidráulicas', 'Oportunidad', 'Cofre comunitario'),
(6, 'En Monopoly estándar ¿Cuál es el alquiler si aterrizas en Park Place sin casas?"', '$35', '$30', '$50', '$45'),

(6, 'En la serie de televisión "Person of Interest" ¿Quién interpreta al personaje de "Harold Finch"?', 'Michael Emerson', 'Jim Caviezel', 'Kevin Chapman', 'Taraji P. Henson'),
(6, '¿En qué año la compañía de televisión BBC lanzó oficialmente el canal BBC One?', '1936', '1948', '1932', '1955'),
(6, 'En Dos hombres y medio ¿Cuál es el nombre del hijo de Alan Harper?', 'Jake', 'John', 'Jeremy', 'James'),
(6, '¿Quién interpretó al "Bebé Sol" en la serie original de "Teletubbies"?', 'Jessica Smith', 'Pui Fan Lee', 'Sue Monroe', 'Lisa Brockwell'),
(6, '¿Cómo se llamaba el pato inflable sacrificado a la multitud al final de ¿Episodio 34 de la temporada 18 de Gran Hermano?', 'Pablo', 'Esteban', 'Carlos', 'Duckster'),
(6, '¿Qué personaje interpretó Dustin Diamond en la comedia: "Salvados por la campana"', 'Screech', 'Zack', 'Mr. Belding', 'AC Slater'),
(6, 'En el programa de televisión "M*A*S*H" ¿cuál era el apodo del cabo Walter O´Reilly?', 'Radar', 'Hawkeye', 'Hot Lips', 'Trapper'),
(6, '¿Cuál de los siguientes premios NO tienen Matt Stone y Trey Parker?', 'Oscar', 'Emmy', 'Tony', 'Grammy'),
(6, 'En la primera temporada del drama político de Netflix "House of Cards" ¿Qué cargo gubernamental ocupa Frank Underwood?', '"House Majority Whip"', 'Fiscal General', 'Presidente', 'Jefe de Gabinete'),
(6, 'En el programa de televisión de ciencia ficción Doctor Who ¿Quién interpreta al décimo doctor?', 'David Tennant', 'William Hartnell', 'Peter Capaldi', 'Peter Davison'),
(6, '¿Quién interpretó a la camarera en el sketch spam de "Monty Python´s Flying Circus"?', 'Terry Jones', 'Eric Idle', 'Graham Chapman', 'John Cleese'),

(6, '¿Cómo se llama el cómic sobre un niño y un tigre que en realidad es un animal de peluche?', 'Calvin y Hobbes', 'Winnie the Pooh', 'Albert y Pogo', 'Peanuts'),
(6, 'En 1978 ¿Con qué celebridad Superman se asoció para derrotar una invasión alienígena?', 'Muhammad Ali', 'Mike Tyson', 'Sylvester Stallone', 'Arnold Schwarzenegger'),
(6, 'En el universo Hellboy ¿Quién fundó el BPRD?', 'Trevor Bruttenholm', 'Kate Corrigan', 'Johann Kraus', 'Benjamin Daimio'),
(6, 'En el universo anterior a Super Génesis del cómic "Sonic the Hedgehog" ¿Cómo se llamaba el hermano de Sally Acorn?', 'Elias Acorn', 'Maximillian Acorn', 'Alexis Acorn', 'Frederick Acorn'),
(6, 'En los cómics de Batman ¿Con qué apodo se le conoce al villano Dr. Jonathan Crane?', 'El Espantapajaros', 'Bane', 'Hombre Calendario', 'Clayface'),
(6, '¿Cuál es el verdadero nombre de Batman?', 'Bruce Wayne', 'Clark Kent', 'Barry Allen', 'Tony Stark'),
(6, 'En la Webcomic "Homestuck" ¿Cuál es el nombre alternativo de "Kingdom of Lights"?', 'Prospit', 'No Name', 'Golden City', 'Yellow Moon'),
(6, 'En los cómics de DC ¿Dónde vive Green Arrow (Oliver Queen)?', 'Star City', 'Central City', 'Gotham City', 'Metropolis'),
(6, 'Más conocido por su apodo Logan ¿Cuál es el nombre de nacimiento de Wolverine?', 'James Howlett', 'Logan Wolf', 'Thomas Wilde', 'John Savage'),
(6, 'Encontrado en el universo ficticio de Marvel Comics ¿Cómo se llama el metal casi indestructible que recubre los huesos y las garras de Wolverine?', 'Adamantium', 'Titanio', 'Vibranio', 'Carbonadio'),

(6, '¿De qué obra es la cita "El infierno son los demás"?', 'No Exit', 'The Devil and the Good Lord', 'The Condemned of Altona', 'The Flies'),
(6, '¿Quién interpretó al Marqués de Lafayette y a Thomas Jefferson en la presentación original de Hamilton en Broadway?', 'Daveed Diggs', 'Lin-Manuel Miranda', 'Javier Muñoz', 'Wayne Brady'),
(6, '¿En qué obra de Shakespeare encontrarás el suicidio de Ofelia?', 'Hamlet', 'Macbeth', 'Othello', 'King Lear'),
(6, '¿Quién escribió la obra "Angels in America"?', 'Tony Kusher', 'Tom Stoppard', 'Matthew López', 'Anthony Neilson'),
(6, 'En Macbeth ¿A qué especie las brujas usaron sus ojos en el caldero?', 'Tritones', 'Humanos', 'Tiburones', 'Calamares'),

(7, '¿Por qué razón una hiena manchada "reiría"?', 'Nerviosismo', 'Agresión', 'Agotamiento', 'Excitación'),
(7, '¿Cómo se llama la cueva donde se esconden los conejos?', 'Madriguera', 'Guarida', 'Nido', 'Dray'),
(7, '¿De qué tipo de animal es la lana la cachemira?', 'Cabra', 'Oveja', 'Camello', 'Llama'),
(7, '¿Cuál de estos animales NO es un lagarto?', 'Tuatara', 'Dragón de Komodo', 'Monstruo de Gila', 'Iguana verde'),
(7, '¿Qué especie es un "pollo de montaña"?', 'Rana', 'Pollo', 'Caballo', 'Mosca'),
(7, '¿Dónde era originaria la especie ahora extinta "Thylacine"?', 'Tasmania, Australia', 'Baluchistán, Pakistán', 'Valaquia, Rumania', 'Oregón, Estados Unidos'),

(13, '¿Quién era el Rey de los Dioses en la mitología griega antigua?', 'Zeus', 'Apolo', 'Hermes', 'Poseidón'),
(13, '¿Un minotauro es mitad humano mitad qué?', 'Toro', 'Caballo', 'Águila', 'Vaca'),
(13, '¿La marca de ropa y calzado Nike toma su nombre de la diosa griega de qué?', 'Victoria', 'Valor', 'Fuerza', 'Honor'),
(13, '¿Cuál fue el castigo por la astucia de Sísifo?', 'Maldito a hacer rodar una roca colina arriba por la eternidad.', 'Atado a una roca por la eternidad, siendo picoteado por pájaros.', 'Parado en un lago lleno de agua que no podía beber.', 'Derribar un árbol que se regeneraba después de cada golpe de hacha'),
(13, '¿Cuál de estas criaturas mitológicas se dice que son mitad hombre y mitad caballo?', 'Centauro', 'Minotauro', 'Pegaso', 'Gorgona'),
(13, 'Según el folclore algonquino ¿Cómo se transforma uno en Wendigo?', 'Participar en el canibalismo', 'Mutilación excesiva de cadáveres de animales', 'Realización de un ritual que implica asesinato', 'Beber la sangre de muchos animales asesinados'),
(13, '¿Qué dios griego era el dios del sol?', 'Helios', 'Zeus', 'Hades', 'Poseidón'),
(13, '¿Con qué animal dormía la reina Pasipahe antes de dar a luz al Minotauro en la mitología griega?', 'Toro', 'Cerdo', 'Buey', 'Caballo'),
(13, '¿El panteón de Roma fue hecho para adorar a qué dios?', 'Cualquier dios que quisieran', 'Atenea', 'Zeus', 'Atenea y Zeus'),
(13, '¿Qué ex presidente de Estados Unidos utilizó "Let´s Make America Great Again" como su eslogan de campaña antes de la campaña de Donald Trump?', 'Ronald Reagan', 'Jimmy Carter', 'Gerald Ford', 'Richard Nixon'),
(13, '¿Cuál de los siguientes senadores de los Estados Unidos es conocido por realizar un obstruccionismo de 24 horas?', 'Strom Thurmond', 'Roy Blunt', 'John Barrasso', 'Chuck Schumer'),
(13, '¿Quién fue el primer presidente nacido en los Estados Unidos independientes?', 'Martin Van Buren', 'John Adams', 'George Washington', 'James Monroe'),
(13, '¿Quién fue el único presidente que no estuvo en el cargo en Washington DC?', 'George Washington', 'Abraham Lincoln', 'Richard Nixon', 'Thomas Jefferson'),
(13, '¿De quién fue el lema de la campaña presidencial de 2016: "Make America Great Again"?', 'Donald Trump', 'Ted Cruz', 'Marco Rubio', 'Bernie Sanders'),
(13, 'En junio de 2017 ¿Con qué país Arabia Saudita y Egipto rompieron relaciones por su supuesto apoyo al terrorismo?', 'Qatar', 'Bahréin', 'Estados Unidos', 'Rusia'),
(13, 'Entre 1973 y 1990 ¿Qué país fue gobernado por el dictador Augusto Pinochet?', 'Chile', 'Etiopía', 'Indonesia', 'Nicaragua'),
(13, '¿Qué letra necesitas tener en una licencia de conducir europea para conducir cualquier motocicleta?', 'A', 'D', 'B', 'X'),
(13, '¿Qué comediante interpreta a Neil Hamburger?', 'Gregg Turkington', 'Nathan Fielder', 'Tim Heidecker', 'Todd Glass'),
(13, '¿Cuántos pies mide Tom Cruise?', '5,7', '5,9', '5,4', '5,5'),
(13, '¿En qué año fue absuelto OJ Simpson de sus cargos de asesinato?', '1995', '1992', '1996', '1991'),
(13, '¿Con qué nombre se conoce mejor a Ramón Estevez?', 'Martin Sheen', 'Charlie Sheen', 'Ramon Sheen', 'Emilio Estevez'),
(13, '¿En qué año murió "Bob Ross"?', '1995', '1986', '1989', '1997'),
(13, 'Aubrey Graham es mejor conocido como:', 'Drake', 'Travis Scott', 'Lil Wayne', '2 Chainz'),
(13, '¿Qué locutor de radio se hace llamar "El Rey de todos los medios"?', 'Howard Stern', 'Rush Limbaugh', 'Pete Tong', 'Ryan Seacrest'),
(13, 'En 2014 ¿Qué rapero de Top 100 que apareció en "Computers" y "Body Dance" fue arrestado en una operación encubierta por la policía de Nueva York por asesinato?', 'Bobby Shmurda', 'DJ Snake', 'Swae Lee', 'Young Thug'),
(13, '¿Cuál de estos NO es un modelo de automóvil producido por el fabricante de automóviles de Malasia Proton?', 'Kelisa', 'Saga', 'Perdana', 'Inspira'),
(13, '¿Cuántos caballos de fuerza produce la locomotora SD40-2?', '3.000', '3.200', '2.578', '2.190'),
(13, '¿Cuál de estas empresas NO fabrica automóviles?', 'Ducati', 'Nissan', 'GMC', 'Fiat'),
(13, '¿Qué marca de automóvil NO pertenece a General Motors?', 'Ford', 'Buick', 'Cadillac', 'Chevrolet'),

(8, '¿Cuál fue el primer deporte que se jugó en la luna?', 'Golf', 'Tenis', 'Fútbol', 'Fútbol americano'),
(8, '¿En qué año se fundó Canadá?', '1867', '1859', '1798', '1668'),
(8, 'Directamente entre el Monumento a Washington y el Reflecting Pool hay un monumento ¿A qué guerra se monumenta?', 'Segunda Guerra Mundial', 'Guerra de Vietnam', 'Guerra Civil Estadounidense', 'Guerra Revolucionaria Estadounidense'),
(8, 'Cuántos años duró la guerra de cien años?', '116', '100', '90', '101'),
(8, 'Ordene los siguientes imperios iraníes en orden cronológico:', 'Mediana, aqueménida, parto, sasánida', 'Mediana, aqueménida, sasánida, parto', 'Aqueménida, mediana, parto, sasánida', 'Aqueménida, mediana, sasánida, parto'),
(8, '¿Cuál de los siguientes físicos ayudó a la Alemania nazi en la producción de un arma nuclear?', 'Werner Heisenberg', 'John von Neumann', 'Albert Einstein', 'Max Planck'),
(8, '¿A quién se atribuye primero el argumento ontológico para la prueba de la existencia de Dios?', 'Anselmo de Canterbury', 'René Descartes', 'Immanuel Kant', 'Aristóteles'),
(8, '¿De qué nacionalidad era el sultán Saladino?', 'Kurdo', 'Árabe', 'Egipcio', 'Sirio'),
(8, '¿Cuándo se creó la Agencia de Seguridad Nacional de los Estados Unidos?', '4 de noviembre de 1952', '26 de julio de 1908', '1 de julio de 1973', '25 de noviembre de 2002'),
(8, '¿A qué evento histórico hace referencia la Obertura de 1812 de Tchaikovsky?', 'Las guerras napoleónicas', 'La guerra estadounidense de 1812', 'La Revolución Rusa', 'La carga de la Brigada Ligera (Guerra de Crimea)'),
(8, '¿Qué emperador del Imperio Bizantino encargó Santa Sofía?', 'Justiniano I', 'Constantino IV', 'Arcadio', 'Teodosio el Grande'),
(8, '¿Cuándo abandonó Canadá la confederación para convertirse en su propia nación?', '1 de julio de 1867', '1 de julio de 1763', '1 de julio de 1832', '1 de julio de 1902'),
(8, '¿Cuál de estos padres fundadores de los Estados Unidos de América llegó a ser presidente?', 'James Monroe', 'Alexander Hamilton', 'Samuel Adams', 'Roger Sherman'),
(8, '¿Qué comandante militar famoso dirigió un ejército, que incluía elefantes de guerra, sobre los Alpes durante la Segunda Guerra Púnica?', 'Hannibal', 'Garmanicus', 'Alexander el Genial', 'Tiberius'),
(8, '¿Quién montó a caballo para advertir a los Minutemen que los británicos venían durante la Guerra Revolucionaria de Estados Unidos?', 'Paul Revere', 'Thomas Paine', 'Henry Longfellow', 'Nathan Hale'),
(8, '¿Qué rey fue asesinado en la batalla de Bosworth Field en 1485?', 'Richard III', 'Edward V', 'Henry VII', 'James I'),
(8, '¿Qué fabricante diseñó la minigun en 1960?', 'General Electric', 'Colt Firearms', 'Heckler & Koch', 'Sig Sauer'),
(8, 'Cuando Cristóbal Colón navegó hacia América ¿Cuál fue la primera región a la que llegó?', 'Archipiélago de las Bahamas', 'Florida', 'Istmo de Panamá', 'Nicaragua'),
(8, 'Durante las invasiones mongolas a Japón ¿Qué detuvó principalmente a los barcos mongoles?', 'Tifones', 'Tornados', 'Depresión económica', 'Samurai'),
(8, 'En 1453 ¿Qué ciudad importante cayó?', 'Constantinopla', 'Roma', 'Hamburgo', 'Atenas'),
(8, '¿Cuál es el número de casco clase destructora Fletcher?"', 'DD-445', 'DD-992', 'DD-444', 'DD-446'),
(8, '¿Cuál de las siguientes NO está clasificada como lengua semética?', 'Sumerio', 'Maltés', 'Acadio', 'Mandaico'),
(8, 'Estos dos países formaron una comunidad entre los siglos XVI y XVIII', 'Polonia y Lituania', 'Hutu y Ruanda', 'Corea del Norte y Corea del Sur Corea', 'Bangladesh y Bután'),
(8, '¿Cómo era más conocido William Frederick Cody?', 'Buffalo Bill', 'Billy the Kid', 'Wild Bill Hickok', 'Pawnee Bill'),
(8, '¿En qué prisión estuvo recluido Adolf Hitler en 1924?', 'Prisión de Landsberg', 'Prisión de Spandau', 'Abadía de Ebrach', 'Hohenasperg'),
(8, '¿Con qué tratado terminó la "Guerra de los Treinta Años"?', 'Paz de Westfalia', 'Tratado de Versalles', 'Tratado de París', 'Paz de Praga'),
(8, '¿Qué edificio fue incendiado el 24 de agosto de 1812?', 'La Casa Blanca', 'Edificio del Parlamento', 'Edificio de la Gran Asamblea Nacional', 'Palacio de la Nación'),
(8, '¿Cómo se llama el avión de serie "Boeing B-29" que arrojó la bomba atomica "Little Boy" en Hiroshima?', 'Enola Gay', 'Necessary Evil', 'The Great Artiste', 'Full House'),
(8, '¿Cómo fue ejecutado Sócrates?', 'Envenenado', 'Decapitado', 'Fusilado por el pelotón', 'Crucificado'),
(8, '¿Cuándo concluyó la Gran Guerra Patria en la URSS?', '9 de mayo de 1945', '2 de septiembre de 1945', '9 de agosto de 1945', '11 de diciembre de 1945'),
(8, '¿Qué edad tenía el rey Enrique V cuando murió?', '35', '62', '87 ', '73'),
(8, 'El alfabeto romano original carecía de las siguientes letras EXCEPTO:', 'X', 'W', 'U', 'J'),
(8, '¿Cuándo fue nombrado Adolf Hitler Canciller de Alemania?', '30 de enero de 1933', '1 de septiembre de 1939', '27 de febrero de 1933', '6 de octubre de 1939'),
(8, '¿Cuánto duró el Levantamiento de Varsovia durante la Segunda Guerra Mundial?', '63  Días', '20  Días', '55  Días', '224  Días'),
(8, '¿Cuándo Jamaica recibió su independencia de Inglaterra?', '1962', '1492', '1963', '1987');
